from photometry.io.excel import load_excel
from photometry.io.bundles import (
    canonicalize_session,
    load_processed_bundles,
    load_session_dataset,
    load_sessions,
    extract_processed_fp_sessions,
)
from photometry.pipelines.preprocess_bundle import prepare_bundle, PrepareBundleConfig
from photometry.metrics.photometry import time_to_peak_inhibition, compute_fp_peak_delta_z, auc_blocks, auc_blocks_from_cfg
from photometry.plotting import (
    build_matrix,
    compute_group_average,
    plot_group_average,
    plot_dataset_comparison,
    plot_two_group_bar,
    plot_session_summary,
    prepare_session_matrix,
    plot_multi_signal_summary,
    plot_cross_correlation_summary,
    plot_metrics_by_group,
)

from photometry.analysis import (
    GlucoseAnalysisConfig,
    compute_glucose_derivative,
    compute_glucose_metrics,
    compute_incremental_auc,
    detect_glucose_onset,
    EarlyModelConfig,
    prepare_early_model_session,
    select_early_model_data,
    fit_early_model,
    residualize_early_model,
    fit_and_residualize_early_model,
    CrossCorrelationConfig,
    compute_cross_correlation,
    compute_session_cross_correlations,
    CircularShiftConfig,
    generate_circular_shift_nulls,
    compute_circular_shift_correlation_null,
)

__all__ = [
    "GlucoseAnalysisConfig",
    "compute_glucose_derivative",
    "compute_glucose_metrics",
    "compute_incremental_auc",
    "detect_glucose_onset",
    "EarlyModelConfig",
    "prepare_early_model_session",
    "select_early_model_data",
    "fit_early_model",
    "residualize_early_model",
    "fit_and_residualize_early_model",
    "CrossCorrelationConfig",
    "compute_cross_correlation",
    "compute_session_cross_correlations",
    "CircularShiftConfig",
    "generate_circular_shift_nulls",
    "compute_circular_shift_correlation_null",
    "load_excel",
    "canonicalize_session",
    "load_processed_bundles",
    "load_session_dataset",
    "load_sessions",
    "extract_processed_fp_sessions",
    "prepare_bundle",
    "PrepareBundleConfig",
    "time_to_peak_inhibition",
    "compute_fp_peak_delta_z",
    "auc_blocks",
    "auc_blocks_from_cfg",
    "build_matrix",
    "compute_group_average",
    "plot_group_average",
    "plot_dataset_comparison",
    "plot_two_group_bar",
    "plot_session_summary",
    "prepare_session_matrix",
    "plot_multi_signal_summary",
    "plot_cross_correlation_summary",
    "plot_metrics_by_group",
]